name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 或 macOS（如需 iOS 构建）

    steps:
      - uses: actions/checkout@v4

      # 下载 Flutter 3.0.0 SDK（Linux 示例）
      - name: Download Flutter 3.0.0
        run: |
          wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.0.0-stable.tar.xz
          tar xf flutter_linux_3.0.0-stable.tar.xz
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      # 验证安装
      - name: Check Flutter Version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

      # 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 代码分析
      - name: Analyze
        run: flutter analyze

      # 运行测试
      - name: Run tests
        run: flutter test

      # （可选）构建 APK/IPA
      # - name: Build APK
      #   run: flutter build apk --release
