name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: slave-l1
    
    steps:
      - uses: actions/checkout@v4

      # 1. 安装 Flutter 3.0.0
      - name: Install Flutter 3.0.0
        run: |
          flutter --version

      # 2. 验证安装（使用完整路径确保可靠）
      - name: Verify Installation
        run: |
          $FLUTTER_HOME/bin/flutter --version
          which flutter

      # 3. 安装依赖
      - name: Install dependencies
        run: flutter pub get

      # 4. 运行测试
      - name: Run tests
        run: flutter test
